import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "./_components/common/topBar/Header";
import ThemeProvider from "./providers/ThemeProvider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: [ "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="dark:bg-gray-900" lang="en"  suppressHydrationWarning>
      <body className={poppins.className + " dark:text-gray-200 text-gray-600 font-light"}>
        <ThemeProvider>
          <main className="max-w-6xl mx-auto flex  min-h-screen flex-col justify-start items-center ">
            <Header />
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
