import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import Header from "./_components/common/topBar/Header";

const poppins = Poppins({ subsets: ["latin"],weight:["300","500","700","900"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={poppins.className}>
        <ThemeProvider>
          <main className="max-w-2xl flex flex-col justify-start">
            <Header/>
          {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
